name: Docker

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - "*"

env:
  GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Build docker container image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: docker.io/anzbank/sysl-go
          push: false
          tag_with_ref: true
          add_git_labels: true
          tags: latest
          build_args: SYSLGO_VERSION=${{ github.ref }}
          labels: org.opencontainers.image.revision=${{ github.sha }},org.opencontainers.image.url=https://sysl.io

      - name: Test container image
        uses: plexsystems/container-structure-test-action@v0.1.0
        with:
          # this is intended to resolve to the local docker image we just built above
          image: anzbank/sysl-go:latest
          config: container-structure-tests.yaml
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: docker.io/anzbank/sysl-go

      - name: Build and push docker container image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: docker.io/anzbank/sysl-go
          # only attempt to push if we are in the open source repo that has credentials, and there's been a push, not merely a pull request.
          push: ${{ github.repository == 'anz-bank/sysl-go' && github.event_name == 'push'}}
          tag_with_ref: true
          add_git_labels: true
          tags: latest
          build_args: SYSLGO_VERSION=${{ github.ref }}
          labels: org.opencontainers.image.revision=${{ github.sha }},org.opencontainers.image.url=https://sysl.io
