name: Lint and Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:1.14-stretch
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run tests
        run: make check-coverage

      - name: Check go mod is tidy
        run: make check-tidy

      - name: Test against downstream repos
        env:
          DOWNSTREAM_TEST: ${{ secrets.DOWNSTREAM_TEST }}
          ORG_GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        run: eval "${DOWNSTREAM_TEST:-echo 'no downstream repos to test'}"
